# Generated by Django 4.1.6 on 2023-02-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('OF', 'OFFICE'), ('ST', 'STUDY'), ('IP', 'IMPORTANT')], max_length=2)),
                ('title', models.TextField(default='', null=True)),
                ('goal', models.TextField(default='', null=True)),
                ('is_alarm', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='todo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Todo',
                'managed': True,
            },
        ),
    ]
