# Generated by Django 4.1.6 on 2023-02-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('OFFICE', 'OFFICE'), ('STUDY', 'STUDY'), ('IMPORTANT', 'IMPORTANT')], max_length=10),
        ),
        migrations.CreateModel(
            name='TodoDay',
            fields=[
                ('todo_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('todo_id', models.ForeignKey(db_column='todo_id', on_delete=django.db.models.deletion.CASCADE, related_name='routine_day', to='todo.todo')),
            ],
            options={
                'db_table': 'TodoDay',
                'managed': True,
            },
        ),
    ]
